Repository pagopa/pagopa-cruscotto-backend, pull requests merged in 2025-05, with the labels that each got.

#11 chore: Disable-cors-filter
  src/main/java/com/nexigroup/pagopa/cruscotto/config/WebConfigurer.java
Labels: patch

#12 feat: Add cors disabled and removed subkey ( use JWT )
  infra/04_apim_api.tf
  infra/policy/_base_policy.xml
Labels: ignore-for-release

#14 Fix build
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application.yml
  src/test/java/com/nexigroup/pagopa/cruscotto/TechnicalStructureTest.java
  src/test/java/com/nexigroup/pagopa/cruscotto/config/WebConfigurerTest.java
  src/test/resources/config/application.yml
Labels: size/small, patch

#16 Edit openapi
  openapi/openapi.json
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AnagPartnerResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AuthFunctionResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AuthGroupResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AuthPermissionResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AuthUserResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/InstanceResource.java
Labels: size/small, patch

#19 fix build error
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AccountResource.java
Labels: size/small, patch

#20 V2.1
  src/main/java/com/nexigroup/pagopa/cruscotto/domain/Instance.java
  src/main/resources/db/migration/liquibase/changelog/1.0.0/ddl/20250505112400_added_entity_PagoPaRecordedTimeout.xml
  src/main/resources/db/migration/liquibase/changelog/1.0.0/ddl/20250505113100_added_entity_PagoPaTaxonomyAggregatePosition.xml
Labels: size/small, patch

#21 feat: Fix pipelines db-migration & update infra api
  .github/workflows/04h_deploy_with_github_runner.yml
  .github/workflows/09_db_migration_with_github_runner.yml
  infra/.terraform.lock.hcl
  infra/04_apim_api.tf
  infra/99_main.tf
  infra/env/weu-dev/backend.tfvars
  infra/env/weu-prod/backend.tfvars
  infra/env/weu-uat/backend.tfvars
Labels: size/small, patch

#22 V2.2
  openapi/openapi.json
  pom.xml
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AnagPartnerService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagPartnerServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AnagPartnerResource.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-devpagopa.yml
  src/main/resources/db/migration/liquibase/properties/crusc8.properties
  src/main/resources/logback-spring.xml
Labels: size/small, patch

#26 2.3
  src/main/resources/config/application-devpagopa.yml
  src/main/resources/config/application.yml
Labels: size/small, patch

#23 chore: Test liquid cmd
  .github/workflows/09_db_migration_with_github_runner.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_variables.tf
Labels: ignore-for-release, size/small, skip

#31 2.4 - fix deploy
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/a1/KpiA1Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/b2/KpiB2Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/b9/KpiB9Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/InstanceResource.java
  src/main/resources/config/application-dev.yml
Labels: size/large, patch

#32 2.4
  src/main/resources/db/migration/liquibase/changelog/1.0.1/ddl/20250530140600_alter_entity_Module.xml
Labels: size/small, patch
