Repository pagopa/pagopa-cruscotto-backend, pull requests merged in 2025-04, with the labels that each got.

#4 chore: Update pipelines
  .devops/db-users-schema-pipelines.yml
  .github/workflows/00_add_patch_label.yml
  .github/workflows/01_anchore.yml
  .github/workflows/01_assignee.yml
  .github/workflows/02_check_pr.yml
  .github/workflows/03_code_review.yml
  .github/workflows/04_release_and_deploy.yml
  .github/workflows/04h_deploy_with_github_runner.yml
  .github/workflows/05_update_code.yml
  .github/workflows/06_integration_test.yml
  .github/workflows/07_performance_test.yml
  .github/workflows/08_create_dashboard.yml
  .github/workflows/09_db_migration_with_github_runner.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/github_scripts/check_required_labels.js
  .github/workflows/github_scripts/check_size.js
  .github/workflows/integration_test.yml
  .gitignore
Labels: ignore-for-release

#5 Fix for deploy
  .devops/db-users-schema-pipelines.yml
  Dockerfile
  helm/values-dev.yaml
  openapi/openapi.json
  src/main/java/com/nexigroup/pagopa/cruscotto/job/plannedshutdown/LoadPlannedShutdownJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/taxonomy/LoadTaxonomyJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagPlannedShutdownServiceImpl.java
  src/main/resources/config/application-prod.yml
  src/main/resources/config/liquibase/master.xml
Labels: patch

#6 chore: Fix docker file
  .env.copy
  .gitignore
  Dockerfile
  src/main/resources/config/application-devpagopa.yml
Labels: size/small, patch

#7 chore: Add apim infra
  .gitignore
  helm/values-dev.yaml
  infra/.terraform.lock.hcl
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/policy/_base_policy.xml
Labels: ignore-for-release

#9 Update README.md
  README.md
Labels: ignore-for-release, size/small
