Repository pagopa/pagopa-cruscotto-backend, pull requests merged in 2025-09, with the labels that each got.

#84 2.22
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/CalculateStateInstanceJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/CalculateStateInstanceService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/CalculateStateInstanceServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/InstanceServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/InstanceModuleResource.java
Labels: patch

#88 chore: Upd codeowner
  CODEOWNERS
Labels: ignore-for-release, size/small, skip

#90 Releases/crus 101 v0.1
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/b9/KpiB9Job.java
Labels: size/small, patch

#94 Releases/crus 101 v0.1
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/b2/KpiB2Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/KpiB9AnalyticDataServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/KpiB9DetailResultServiceImpl.java
Labels: size/small, patch
