Repository pagopa/pagopa-cruscotto-backend, pull requests merged in 2025-08, with the labels that each got.

#65 2.15
  openapi-acn/openapi-acn.json
  src/main/java/com/nexigroup/pagopa/cruscotto/domain/AnagPartner.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/cache/LoadRegistryJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/CalculateStateInstanceJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AnagPartnerService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AnagStationService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/AnagPartnerDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/AnagPartnerFilterDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/PartnerIdentificationDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/filter/AnagStationFilter.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagPartnerServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagStationServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/mapper/AnagPartnerMapper.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/validation/DateValidator.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/validation/ValidDate.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AnagPartnerResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AnagStationResource.java
  src/main/resources/ValidationMessages.properties
  src/main/resources/ValidationMessages_en.properties
  src/main/resources/ValidationMessages_it.properties
  src/main/resources/config/application-local.yml
  src/main/resources/config/application.yml
  src/main/resources/db/migration/liquibase/changelog/1.0.5/ddl/20250711122000_alter_entity_AnagPartner.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.5.xml
  src/main/resources/logback-spring.xml
  src/test/java/com/nexigroup/pagopa/cruscotto/job/cache/LoadRegistryJobIT.java
  src/test/java/com/nexigroup/pagopa/cruscotto/service/AnagPartnerServiceImplIT.java
  src/test/java/com/nexigroup/pagopa/cruscotto/service/AnagStationServiceImplIT.java
  src/test/resources/config/application.yml
Labels: size/large, patch

#68 Update CODEOWNERS with andrea-invernizzi8
  CODEOWNERS
Labels: size/small, patch

#67 2.15
  openapi/openapi.json
Labels: size/small, patch

#71 chore: Update CODEOWNERS
  CODEOWNERS
Labels: size/small, patch, skip

#72 2.16
  src/test/resources/config/application.yml
Labels: size/small, patch

#75 Fix openapi.json senza management resources
  openapi/openapi.json
Labels: size/small, patch

#76 Aggiornamento openapi.json
  openapi/openapi.json
Labels: size/small, patch

#77 2.16
  openapi/openapi.json
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AnagPartnerResource.java
Labels: size/small, patch

#78 2.17
  src/main/java/com/nexigroup/pagopa/cruscotto/domain/AnagPartner.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/cache/LoadRegistryJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/repository/AnagInstitutionRepository.java
  src/main/java/com/nexigroup/pagopa/cruscotto/repository/AnagStationAnagInstitutionRepository.java
  src/main/java/com/nexigroup/pagopa/cruscotto/repository/AnagStationRepository.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AnagPartnerService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AnagStationService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/AnagPartnerDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagInstitutionServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagPartnerServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagStationServiceImpl.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-local.yml
  src/main/resources/db/migration/liquibase/changelog/1.0.7/ddl/20250805150000_add_institutions_count_to_anag_partner.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.7.xml
Labels: size/small, patch

#79 2.18
  openapi/openapi.json
  src/main/java/com/nexigroup/pagopa/cruscotto/security/AuthoritiesConstants.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/InstanceModuleService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/InstanceModuleUpdateStatusDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/InstanceModuleServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/InstanceModuleResource.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-local.yml
  src/main/resources/db/migration/liquibase/changelog/1.0.8/dml/20250811101600_add_entity_authorizations.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.8.xml
  src/test/java/com/nexigroup/pagopa/cruscotto/service/impl/InstanceModuleServiceImplTest.java
Labels: size/large, patch

#81 2.19
  openapi/openapi.json
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/a2/KpiA2Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/PagoPaTaxonomyAggregatePositionService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/PagoPaTaxonomyIncorrectDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagPartnerServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/PagoPaTaxonomyAggregatePositionServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/util/TaxonomyValidationUtils.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/PagoPaTaxonomyAggregatePositionResource.java
Labels: patch

#82 2.20
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-devpagopa.yml
  src/main/resources/config/application-local.yml
  src/main/resources/db/migration/liquibase/changelog/1.0.9/dml/20250826120000_sync_anag_partner_from_instance.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.9.xml
  src/test/resources/config/application.yml
Labels: size/small, patch
