Repository pagopa/pagopa-cruscotto-backend, pull requests merged in 2025-06, with the labels that each got.

#34 2.5
  openapi/openapi.json
  pom.xml
  src/main/java/com/nexigroup/pagopa/cruscotto/config/ApplicationProperties.java
  src/main/java/com/nexigroup/pagopa/cruscotto/config/QuartzConfiguration.java
  src/main/java/com/nexigroup/pagopa/cruscotto/domain/QrtzLogTriggerExecuted.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/config/DbLoggingJobListener.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/config/DbLoggingTriggerListener.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/a1/KpiA1Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/b9/KpiB9Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/repository/QrtzLogTriggerExecutedRepository.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/JobService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/KpiB9AnalyticDataService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/KpiB9DetailResultService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/QrtzLogTriggerExecutedService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/JobsDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/QrtzLogTriggerExecutedDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/filter/JobExecutionFilter.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/JobServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/KpiB9AnalyticDataServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/KpiB9DetailResultServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/QrtzLogTriggerExecutedServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/mapper/QrtzLogTriggerExecutedMapper.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/JobControllerResources.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/KpiAnalyticDataResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/KpiDetailResultResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/KpiResultResource.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-devpagopa.yml
  src/main/resources/config/application.yml
  src/main/resources/db/migration/liquibase/changelog/1.0.2/ddl/20250603151000_alter_entity_QrtzLogTriggerExecuted.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.2.xml
Labels: patch

#35 2.5
  src/main/java/com/nexigroup/pagopa/cruscotto/config/ApplicationProperties.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/config/ClearLogConfigJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/config/JobConstant.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/log/ClearLogJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/repository/QrtzLogTriggerExecutedRepository.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/QrtzLogTriggerExecutedService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/JobServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/QrtzLogTriggerExecutedServiceImpl.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-devpagopa.yml
  src/test/resources/config/application.yml
Labels: size/small, patch

#38 Update application-devpagopa.yml
  src/main/resources/config/application-devpagopa.yml
Labels: size/small, patch

#39 Update KpiA1Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/a1/KpiA1Job.java
Labels: size/small, patch

#40 Update PagoPaCruscottoBackendApp.java
  src/main/java/com/nexigroup/pagopa/cruscotto/PagoPaCruscottoBackendApp.java
Labels: size/small, patch

#48 fix: UAT env
  .terraform-version
  infra/env/weu-uat/terraform.tfvars
Labels: size/small, patch, skip

#49 2.7
  src/main/resources/db/migration/liquibase/changelog/1.0.2/ddl/20250603151000_add_entity_QrtzLogTriggerExecuted.xml
  src/main/resources/db/migration/liquibase/changelog/1.0.2/ddl/20250603151000_alter_entity_QrtzLogTriggerExecuted.xml
  src/main/resources/db/migration/liquibase/changelog/1.0.3/ddl/20250611100000_alter_entity_Module.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.2.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.3.xml
Labels: size/small, patch

#50 2.7
  src/main/resources/db/migration/liquibase/changelog/1.0.3/ddl/20250611100000_alter_entity_Module.xml
Labels: size/small, patch

#51 fix openapi.json
  openapi/openapi.json
Labels: size/small, patch

#53 2.8
  openapi/openapi.json
  src/main/java/com/nexigroup/pagopa/cruscotto/config/ApplicationProperties.java
  src/main/java/com/nexigroup/pagopa/cruscotto/domain/AuthGroup.java
  src/main/java/com/nexigroup/pagopa/cruscotto/security/AuthoritiesConstants.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AnagPartnerService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AnagStationService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AuthUserService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/PagoPaPaymentReceiptService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/PagoPaRecordedTimeoutService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/PagoPaTaxonomyAggregatePositionService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/AnagPartnerDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/dto/AnagStationDTO.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagPartnerServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagStationServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/PagoPaPaymentReceiptServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/PagoPaRecordedTimeoutServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/PagoPaTaxonomyAggregatePositionServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/mapper/AnagStationMapper.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AnagPartnerResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AnagStationResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/PagoPaPaymentReceiptResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/PagoPaRecordedTimeoutResource.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/PagoPaTaxonomyAggregatePositionResource.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-devpagopa.yml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.4.xml
Labels: size/large, patch

#54 2.8
  src/main/resources/db/migration/liquibase/changelog/1.0.4/dml/20250612143000_added_entity_authorizations.xml
Labels: size/small, patch

#56 2.10
  .env.copy
  helm/values-dev.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/com/nexigroup/pagopa/cruscotto/config/AwsClientConfig.java
  src/main/java/com/nexigroup/pagopa/cruscotto/config/AwsRequestLoggingInterceptor.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/MailService.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-devpagopa.yml
  src/main/resources/config/application.yml
  src/test/resources/config/application.yml
Labels: patch

#58 2.10
  .env.copy
Labels: size/small, patch

#60 2.12
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/CalculateStateInstanceJob.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/a1/KpiA1Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/a2/KpiA2Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/b2/KpiB2Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/b9/KpiB9Job.java
Labels: size/large, patch

#61 2.12
  src/main/java/com/nexigroup/pagopa/cruscotto/job/kpi/b2/KpiB2Job.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/AnagPartnerService.java
  src/main/java/com/nexigroup/pagopa/cruscotto/service/impl/AnagPartnerServiceImpl.java
  src/main/java/com/nexigroup/pagopa/cruscotto/web/rest/AnagPartnerResource.java
  src/main/resources/config/application-dev.yml
Labels: size/small, patch
